### ISSUE TITLE
expire with namespace

### ISSUE THREAD

**Issue by brewster1134** [brandonaaron/livequery#15]
Is it possible to expire livequery associations using jquery's event namespacing?

``` js
$('a').livequery('expire', 'click.namespace');
```

**Comment by brandonaaron** [comment]
I apologize for not getting back to you on this. I believe namespaces should have worked, since behind the scenes the jQuery event methods were used to bind ($.fn.bind) and unbind ($.event.remove). However, this was never officially supported or tested.

The rewrite of the plugin that is happening now removes the event handling functionality and only handles the dom changes.
